# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-27 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20211027_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_names',
            new_name='name',
        ),
    ]
