# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20211027_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='message',
            field=models.TextField(),
        ),
    ]
